apiVersion: v1
kind: Pod
metadata:
  name: nfs-debug
  namespace: mlp-explorer-prod
spec:
  serviceAccountName: default
  containers:
  - name: debug
    image: ubuntu:22.04
    command: ['sleep']
    args: ['3600']
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-test
      mountPath: /mnt/nfs-test
  volumes:
  - name: nfs-test
    persistentVolumeClaim:
      claimName: mlp-nfs-pvc-prod
  restartPolicy: Never
