apiVersion: v1
kind: Pod
metadata:
  name: nfs-tools-test
  namespace: mlp-explorer-prod
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nfs-tools
      image: alpine:latest
      command: ["/bin/sh", "-c", "apk add --no-cache nfs-utils && sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL