apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlp-nfs-pvc
  namespace: mlp-explorer-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  # Explicitly link to the existing PV name that the sysadmins control
  volumeName: mlp-nfs-pv