apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlp-nfs-pvc-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: mlp-prod-nfs-pv