apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlp-nfs-pvc-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: mlp-test-nfs-pv