apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-postgres-egress
  namespace: mlp-explorer-test
spec:
  podSelector: {} # This applies to ALL pods in the namespace
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 5432
    # No 'to' field means 'allow to any destination'